### PR TITLE
MFEMSidreDataCollection fixes for FESpace caching and parallel saving

### LINKED ISSUE #726: MFEMSidreDataCollection is too eager to cache FESpaces
Currently we just use the basis name of the FEColl to see if FESpaces are equivalent but we also need to check the ordering.

Proposed solution would be to append something that signifies the ordering onto the basis name.

### LINKED ISSUE #727: MFEMSidreDataCollection + MPI saves the whole datastore
The serial path just saves the blueprint group - I think we can do the same in the parallel case.

Encountered when storing multiple DataCollections in the same datastore.

### PR DESCRIPTION
**Pull request by joshessman-llnl**
# Summary

- This PR is a set of bugfixes
- It does the following:
  - Fixes #726
  - Fixes #727 

The main design change is to attempt to only save a subset of the datastore in parallel (which is already the case in serial).

My initial thought was to create a temporary datastore that has shallow copies of the groups specific to the datacollection, but in order to save groups to a file the corresponding buffers need to be part of the same datastore - that is, shallow-copied groups cannot be saved to a file.  As a secondary approach I was able to use a similar approach but with a temporary group that is deleted after the read or write operation.  The idea is that the structure of the "real" groups is replicated within the temporary group, and those groups (in SidreDataCollection-speak, the domain and global groups) are moved/copied back and forth as necessary.

### CODE REVIEW

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp [hunk 1]
```diff
@@ -868,7 +868,42 @@ void MFEMSidreDataCollection::Load(const std::string& path,
     std::string suffixedPath = endsWith(path, ".root") ? path : path + ".root";
 
     IOManager reader(m_comm);
-    reader.read(m_bp_grp->getDataStore()->getRoot(), suffixedPath);
+    // Get the paths in which the global and domain groups are stored
+    // This allows for a datastire structure other than the one used when this
```
Comment (kennyweiss) [inline src/axom/sidre/core/MFEMSidreDataCollection.cpp:872]: Typo:
```suggestion
    // This allows for a datastore structure other than the one used when this
```

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp [hunk 2]
```diff
@@ -868,7 +868,42 @@ void MFEMSidreDataCollection::Load(const std::string& path,
...
+    // class owns the DataStore
+    Group* global_grp = m_bp_index_grp->getParent()->getParent();
+    Group* domain_grp = m_bp_grp->getParent();
```
Comment (kennyweiss) [inline src/axom/sidre/core/MFEMSidreDataCollection.cpp:875]: Can either of these ever be `null` ?

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp [hunk 3]
```diff
@@ -868,7 +868,42 @@ void MFEMSidreDataCollection::Load(const std::string& path,
...
+    Group* new_domain_group = temp_root->getGroup(domain_grp->getPathName());
+    Group* domain_group_parent = datastore_root;
+    if(!domain_path.empty())
+    {
+      domain_group_parent = datastore_root->getGroup(domain_path);
+    }
+    domain_group_parent->destroyGroup(new_domain_group->getName());
+    domain_group_parent->moveGroup(new_domain_group);
+    // Finally we can delete the temporary group
+    temp_root->getParent()->destroyGroup("_sidre_tmp_load");
```
Comment (kennyweiss) [inline src/axom/sidre/core/MFEMSidreDataCollection.cpp:906]: Do we need to also destroy the data/buffers under this tmp group?

Note: This might depend on https://github.com/LLNL/axom/issues/674

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp [hunk 4]
```diff
@@ -1008,8 +1043,37 @@ void MFEMSidreDataCollection::Save(const std::string& filename,
   if(m_comm != MPI_COMM_NULL)
   {
     IOManager writer(m_comm);
-    sidre::DataStore* datastore = m_bp_grp->getDataStore();
-    writer.write(datastore->getRoot(), num_procs, file_path, protocol);
+
+    // Create a shallow mirror of the DataStore structure that only includes
```
Comment (kennyweiss) [inline src/axom/sidre/core/MFEMSidreDataCollection.cpp:1047]: Does this only output the buffers associated with the current mesh? Or will all buffers be dumped?

File: src/axom/sidre/tests/sidre_mfem_datacollection.cpp [hunk 5]
```diff
@@ -774,6 +774,71 @@ TEST(sidre_datacollection, dc_par_reload_gf)
...
+
+  mfem::H1_FECollection fec(1, mesh.Dimension());
+  mfem::ParFiniteElementSpace first_parfes(&parmesh,
+                                           &fec,
+                                           1,
+                                           mfem::Ordering::byNODES);
+  mfem::ParFiniteElementSpace second_parfes(&parmesh,
+                                            &fec,
+                                            3,
+                                            mfem::Ordering::byVDIM);
```
Comment (kennyweiss) [inline src/axom/sidre/tests/sidre_mfem_datacollection.cpp:794]: Based on the logic above, it would also be good to test a vector-valued grid function that is stored by nodes.
e.g.:
```cpp
  mfem::ParFiniteElementSpace third_parfes(&parmesh,
                                            &fec,
                                            3,
                                            mfem::Ordering::byNODES);
```

File: src/axom/sidre/tests/sidre_mfem_datacollection.cpp [hunk 6]
```diff
@@ -774,6 +774,71 @@ TEST(sidre_datacollection, dc_par_reload_gf)
...
+  mfem::ConstantCoefficient three_and_a_half(3.5);
+  first_gf_write.ProjectCoefficient(three_and_a_half);
+
+  mfem::ConstantCoefficient five_and_a_half(5.5);
+  second_gf_write.ProjectCoefficient(five_and_a_half);
+
+  sdc_writer.SetCycle(0);
+  sdc_writer.Save();
+
+  MFEMSidreDataCollection sdc_reader(testName());
```
Comment (kennyweiss) [inline src/axom/sidre/tests/sidre_mfem_datacollection.cpp:821]: Should this be read into a separate datastore? 
Alternatively, should the datastore be cleared to ensure that reading and writing are happening as expected?

**Review by kennyweiss — COMMENTED** [review]
Thanks @joshessman-llnl !

Perhaps I read too much into the description of https://github.com/LLNL/axom/issues/727, but I was expecting to see an example/test with one datastore and multiple associated `MFEMSidreDataCollections`, where each mesh could be separately dumped.
(I'm not saying this is required, it's just where I thought this was going).

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 2 above)
Comment (joshessman-llnl) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:875]: I think we should be safe here - my interpretation of the `getParent` docs is that it will never return `nullptr`:

https://github.com/LLNL/axom/blob/8478a6f3552f68af66bb11ae18a0d516d2d35305/src/axom/sidre/core/Group.hpp#L185-L188

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 3 above)
Comment (joshessman-llnl) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:906]: This is actually intentionally omitted - the intent at least is that the data/buffers under the temporary group were transferred (via `moveGroup`) to the global and domain groups.

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 4 above)
Comment (joshessman-llnl) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:1047]: Regardless of whether MFEMSidreDataColl owns its data the `named_buffers` group exists within the (mesh-specific) domain group:

https://github.com/LLNL/axom/blob/8478a6f3552f68af66bb11ae18a0d516d2d35305/src/axom/sidre/core/MFEMSidreDataCollection.cpp#L101

https://github.com/LLNL/axom/blob/8478a6f3552f68af66bb11ae18a0d516d2d35305/src/axom/sidre/core/MFEMSidreDataCollection.cpp#L134

Accordingly I think only the (named) buffers used by the domain and global groups are saved - additionally this method here

https://github.com/LLNL/axom/blob/8478a6f3552f68af66bb11ae18a0d516d2d35305/src/axom/sidre/core/Group.cpp#L1956-L1958

gets used internally (a couple layers down) to identify the `Buffer`s (managed by the datastore itself) associated with those domain and global groups.

File: src/axom/sidre/tests/sidre_mfem_datacollection.cpp (hunk 6 above)
Comment (joshessman-llnl) [reply src/axom/sidre/tests/sidre_mfem_datacollection.cpp:821]: In this test (and I believe all the others) the datacollections all own their datastores which are created at the time of construction, so I think there wouldn't be anything to clear.  It would be worth adding a test that roughly captures the Serac use case that motivated these changes (per your comment at the top), though.

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 2 above)
Comment (kennyweiss) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:875]: Sorry for not being clearer, I was referring to `m_bp_index_grp` and `m_bp_grp` -- are they always non-null?

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 3 above)
Comment (kennyweiss) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:906]: In that case, please consider adding a comment,
e.g. something like: "Now that the data has been transferred, we can delete the temporary group" ?

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 4 above)
Comment (kennyweiss) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:1047]: That's what I thought (re: `exportTo`).  
Would it make sense to confirm that this is the case?

**Review by kennyweiss — APPROVED** [review]

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 2 above)
Comment (joshessman-llnl) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:875]: I'll add a check for this

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp (hunk 4 above)
Comment (joshessman-llnl) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:1047]: Hmm, I'm not sure what the best way to check this would be since I didn't see any Group methods that report the corresponding buffers (the one used here is `private`), though perhaps I'm just missing something

Comment (kennyweiss) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:1047]: We don't have that built-in.
I was thinking more about manually checking/confirming, e.g. by adding a really large buffer and seeing if this affected the output size.

Comment (joshessman-llnl) [reply src/axom/sidre/core/MFEMSidreDataCollection.cpp:1049]: I've gone ahead and added an an extraneous View to the datastore and later check that it's not reloaded, which I believe confirms the same thing

File: src/axom/sidre/core/MFEMSidreDataCollection.cpp [hunk 7]
```diff
@@ -868,7 +868,44 @@ void MFEMSidreDataCollection::Load(const std::string& path,
...
+    reader.read(temp_root, suffixedPath);
+
+    // First transfer the global group from the temp group to its correct location
+    Group* datastore_root = m_bp_grp->getDataStore()->getRoot();
+    Group* new_global_group = temp_root->getGroup(global_grp->getPathName());
+    Group* global_group_parent = datastore_root;
+    if(!global_path.empty())
+    {
+      global_group_parent = datastore_root->getGroup(global_path);
+    }
```
Comment (rhornung67) [inline src/axom/sidre/core/MFEMSidreDataCollection.cpp:894]: blank lines separating the pieces described in the comments would help readability. Here, after line 897, after 906, etc.

**Review by rhornung67 — CHANGES_REQUESTED** [review]
Looks good. One minor nit about whitespacing.

**Review by rhornung67 — APPROVED** [review]
Thanks  @joshessman-llnl
