### PR TITLE
Fix instantiation of Array::resize

### LINKED ISSUE #1082: Ambiguity in overloaded method Array::resize
The following code doesn't compile due to ambiguity in resolving the overloaded `resize` method:
```
axom::StackArray<axom::IndexType, 2> l2{2,3};
axom::Array<bool, 2> foo2;
foo2.resize(l2, false);

// Similarly for 3D array
axom::StackArray<axom::IndexType, 3> l3{2,3,4};
axom::Array<bool, 3> foo3;
foo3.resize(l3, false);
```
One possible fix could be to require the arguments in ` void resize(Args... args)` to be of integral type, if possible (in addition to having length that matches `DIM`).

### PR DESCRIPTION
**Pull request by publixsubfan**
# Summary

- Fixes an ambiguous call to `Array::resize()` for `axom::Array`s of type `bool`.
  The underlying problem was a protected overload of `resize()` used by the public-facing resize methods; we just rename this to `resizeImpl()` to avoid the ambiguity.

Resolves #1082.

### CODE REVIEW

File: src/axom/core/tests/core_array.hpp [hunk 1]
```diff
@@ -2006,4 +2006,50 @@ TEST(core_array, check_subspan_range)
...
+  EXPECT_EQ(arr3.size(), I_DIMS * J_DIMS * K_DIMS);
+  EXPECT_EQ(arr3.shape()[0], I_DIMS);
+  EXPECT_EQ(arr3.shape()[1], J_DIMS);
+  EXPECT_EQ(arr3.shape()[2], K_DIMS);
+  for(int i = 0; i < I_DIMS; i++)
+  {
+    for(int j = 0; j < J_DIMS; j++)
+    {
+      for(int k = 0; k < K_DIMS; k++) EXPECT_EQ(arr3[i][j][k], value);
+    }
```
Comment (white238) [inline src/axom/core/tests/core_array.hpp:2045]:
```suggestion
      for(int k = 0; k < K_DIMS; k++)
      {
        EXPECT_EQ(arr3[i][j][k], value);
      }
    }
```

**Review by white238 — APPROVED** [review]

**Review by kennyweiss — APPROVED** [review]
Thanks @publixsubfan !

**Review by bmhan12 — APPROVED** [review]

**Review by gunney1 — APPROVED** [review]
Looks good.  Thanks @publixsubfan!
