### PR TITLE
Host/device-aware array operations

### LINKED ISSUE #757: Allow usage of custom `allocatorID` in `PointInCell` constructor
When working through #756, I ran into some problems using a custom `allocatorID` as the fourth parameter for `PointInCell` for a device allocator.

Specifically, the `slam::BitSet` constructor calls `Array::fill()` on its memory to initialize the data in its constructor. 
The bitset constructor is called from PointInCell on the host, and when the data lives on the device the initialization has to happen on the device. Since the current implementation is on the host, the code currently segfaults when using a device allocator.

See:
https://github.com/LLNL/axom/blob/4a6086a3a761abd23e60caf9819bc244469b3f60/src/axom/slam/BitSet.hpp#L151-L152

This is called in the `point_in_cell_mfem` tests, e.g. here:
https://github.com/LLNL/axom/blob/bf08592027382431148e2dc7698d515aee07359d/src/axom/quest/tests/quest_point_in_cell_mfem.cpp#L294

Note: In #756, I had to remove the custom allocator as the fourth parameter. This issue is meant to alleviate this problem.
E.g. we'd like call the function like this:
```cpp
 PointInCellType spatialIndex(m_mesh, GridCell(25).data(), m_EPS, m_allocatorID); 
```
One possible solution would be to improve the logic in `axom::Array` to initialize data based on the memory/execution space. 
Another would be to add an execution space to parameter to `slam::BitSet`.

### PR DESCRIPTION
**Pull request by kanye-quest**
# Summary

- Resolves #757 
- The `axom::Array` functions `clear()`, `fill()`, and `erase()` now handle device memory correctly
  - For non-trivial types in device memory, we copy from/to a host-side temporary buffer in order to execute a copy constructor/destructor - this avoids requiring device-annotated copy constructors/destructors
- `axom::Array` constructors now accept a custom allocator ID when the memory space is specified at compile time, by checking the allocator ID in Umpire for compatibility
- Fixes a potential memory leak when `axom::Array<T>` of non-trivial type is constructed - destructor must be called on elements before buffer is deleted
- Re-enables execution space-specific allocator ID on point-in-cell tests

### CODE REVIEW

File: src/axom/spin/ImplicitGrid.hpp [hunk 1]
```diff
@@ -204,21 +204,19 @@ class ImplicitGrid
     for(int i = 0; i < NDIMS; ++i)
     {
       m_bins[i] = BinSet(m_gridRes[i]);
-      m_binData[i] = BinBitMap(&m_bins[i], BitsetType {}, 1, allocatorID);
+      m_binData[i] =
+        BinBitMap(&m_bins[i], BitsetType(numElts, allocatorID), 1, allocatorID);
```
Comment (kanye-quest) [inline src/axom/spin/ImplicitGrid.hpp:208]: @kennyweiss -- now that we can call `Array::fill` on device memory, initializing `slam::Map` with a Bitset directly should Just Work™; this should fix the performance issue discussed here https://github.com/LLNL/axom/pull/742#discussion_r780523826

File: src/axom/core/Array.hpp [hunk 2]
```diff
@@ -956,18 +941,15 @@ inline typename Array<T, DIM, SPACE>::ArrayIterator Array<T, DIM, SPACE>::erase(
...
-  int counter = 0;
 
-  while(pos < end() - 1)
-  {
-    *pos = *(pos + 1);
-    pos += 1;
-    counter += 1;
-  }
-  (*pos).~T();
+  IndexType posIdx = pos - begin();
```
Comment (rhornung67) [inline src/axom/core/Array.hpp:945]: For methods like this (insert above), I think we should clearly state in the methods documentation what element the returned iterator refers to.

File: src/axom/core/ArrayBase.hpp [hunk 3]
```diff
@@ -533,53 +534,364 @@ struct all_types_are_integral
...
-    axom::copy(data + pos, tmp_buffer, len * sizeof(T));
+    axom::copy(data + begin, tmp_buffer, len * sizeof(T));
     delete[] tmp_buffer;
     return;
   }
-#else
-  AXOM_UNUSED_VAR(alloc_id);
 #endif
-  for(int ielem = 0; ielem < len; ielem++)
+  for(int ielem = begin; ielem < end; ielem++)
```
Comment (rhornung67) [inline src/axom/core/ArrayBase.hpp:593]: Although it doesn't matter here since ielem is an int, I believe that stylistically we prefer pre-fix '++' for consistency across the code.

File: src/axom/core/ArrayBase.hpp [hunk 4]
```diff
@@ -533,53 +534,364 @@ struct all_types_are_integral
...
+ * \param [inout] array the array to fill
+ * \param [in] n the number of elements to fill the array with
+ * \param [in] value the value to set each array element to
+ */
+template <>
+template <typename T, typename ExecSpace>
+void OpFillBase<false>::fill(T* array, IndexType n, const T& value)
+{
+  for_all<ExecSpace>(
+    n,
```
Comment (rhornung67) [inline src/axom/core/ArrayBase.hpp:626]: not a big deal, but was the line break before the first arg intentional?

File: src/axom/core/ArrayBase.hpp [hunk 5]
```diff
@@ -533,53 +534,364 @@ struct all_types_are_integral
...
+template <>
+template <typename T, typename ExecSpace>
+void OpFillBase<true>::fill(T* array, IndexType n, const T& value)
+{
+  void* buffer = ::operator new(sizeof(T) * n);
+  T* typed_buffer = new(buffer) T[n];
+  // If we instantiated a fill kernel here it would require
+  // that T's copy ctor is device-annotated which is too
+  // strict of a requirement, so we copy a buffer instead.
+  for(int i = 0; i < n; i++)
```
Comment (rhornung67) [inline src/axom/core/ArrayBase.hpp:647]:
```suggestion
  for(int i = 0; i < n; ++i)
```

File: src/axom/core/ArrayBase.hpp [hunk 6]
```diff
@@ -533,53 +534,364 @@ struct all_types_are_integral
...
+ */
+template <>
+template <typename T, typename ExecSpace>
+void OpDestroyBase<true>::destroy(T* array, IndexType begin, IndexType end)
+{
+  IndexType n = end - begin;
+  void* buffer = ::operator new(sizeof(T) * n);
+  T* typed_buffer = new(buffer) T[n];
+  axom::copy(typed_buffer, array, sizeof(T) * n);
+  for(int i = begin; i < end; i++)
```
Comment (rhornung67) [inline src/axom/core/ArrayBase.hpp:694]:
```suggestion
  for(int i = begin; i < end; ++i)
```

**Review by rhornung67 — APPROVED** [review]
Looks good. Just a few minor nits to consider.

File: src/axom/spin/ImplicitGrid.hpp (hunk 1 above)
Comment (kennyweiss) [reply src/axom/spin/ImplicitGrid.hpp:208]: Thanks Max!

Re: "should Just Work" -- awesome!
Re: performance issue from #742 -- I'll check it out once you merge this PR.

Comment (kennyweiss) [reply src/axom/spin/ImplicitGrid.hpp:208]: Are you suggesting that I should re-enable initialization in `BitSet`?
(The performance issue I was seeing was on the host using a sequential policy, i.e. unrelated to device memory)

File: src/axom/spin/ImplicitGrid.hpp [hunk 7]
```diff
@@ -204,21 +204,19 @@ class ImplicitGrid
...
-        // We set initial min/max word indices to dummy values. These will be
-        // set correctly on the first call to ImplicitGrid::insert().
-        m_minBlockBin[i][ibin] = numElts;
-        m_maxBlockBin[i][ibin] = 0;
-      }
+
+      // We set initial min/max word indices to dummy values. These will be
+      // set correctly on the first call to ImplicitGrid::insert().
+      m_minBlockBin[i].fill(numElts);
+      m_maxBlockBin[i].fill(0);
```
Comment (kennyweiss) [inline src/axom/spin/ImplicitGrid.hpp:219]: 👍

**Review by kennyweiss — APPROVED** [review]
Thanks @kanye-quest -- this is great!

Did you confirm that our tests have good coverage for all the cases in the new `Op*` structs in `ArrayBase` ?  E.g.  trivially copyable and non-trivially copyable types using host, device and dynamic memory ?

File: src/axom/spin/ImplicitGrid.hpp (hunk 1 above)
Comment (kanye-quest) [reply src/axom/spin/ImplicitGrid.hpp:208]: Oh, looking at that again, I think this fix might be unrelated to your performance issue. (this does fix a segfault with device allocators though)

I think you could either use your current fix, or remove the `m_data.fill(0)` statement in the BitSet constructor, since the array should be initialized to all zeros at construction; both should work.

Comment (kennyweiss) [reply src/axom/spin/ImplicitGrid.hpp:208]: Thanks -- I'll check it out.

I think the specific problem I was trying to fix was in the BitSet's copy constructor called by `ImplicitGrid::getCandidates()`,
which was setting the bits in the copy's array to zero and then copying over the data from the other array
(but I'll look closer).

i.e. in the first line of the following:
https://github.com/LLNL/axom/blob/8d841c0950a93c2d7d2e8c3006f4d59de47df395/src/axom/spin/ImplicitGrid.hpp#L338-L344

#### Context:
This came up in `Delaunay::isValid()` when there were `O(V)` queries with `O(E)` bits each (with `V` and `E` >> 1,000,000) -- so it involved tons of copies, and `findCandidates()` was taking minutes and consuming > 80% of the runtime.

Since each query only really has `O(1)` candidates, I eventually decided to modify the algorithm to only use the `ImplicitGrid` for finding the candidates and then copying this over to a `UniformGrid`.  Each of the `O(V)` queries are then directly against an array of `O(1)` integers.  And there are only `O(<num_bins>)` queries against the `ImplicitGrid`
It's a bit of a kludge, and I'd like to revisit this in the future, but it reduced the runtime of `Delaunay::isValid()` significantly.

File: RELEASE-NOTES.md [hunk 8]
```diff
@@ -32,6 +32,8 @@ The Axom project release numbers follow [Semantic Versioning](http://semver.org/
 - Added initial implementation of GPU/OpenMP-accelerated point-in-cell queries
 - Added an alternative surface mesh tester function to Quest, based on `ImplicitGrid`
 - Add `const` versions of `begin()` and `end()` for `Array` and `ArrayView`
+- Add support for passing compatible custom allocator IDs to `axom::Array` with explicitly specifed
```
Comment (agcapps) [inline RELEASE-NOTES.md:35]:
```suggestion
- Add support for passing compatible custom allocator IDs to `axom::Array` with explicitly specified
```

**Review by agcapps — APPROVED** [review]
Thank you, @kanye-quest .
