### PR TITLE
Fix some C++20 warnings.

### LINKED ISSUE #1670: Fix reported C++20 warnings.
A user compiled Axom with C++20 and asked if we could fix the following warnings:

1:
```
$ROOT/include/axom/fmt/os.h:411:29: warning: inline function 'axom::fmt::ostream::grow' is not defined [-Wundefined-inline]
  411 |   AXOM_FMT_CONSTEXPR20 void grow(size_t) override;
      |                             ^
$ROOT/include/axom/fmt/os.h:413:3: note: used here
  413 |   ostream(cstring_view path, const detail::ostream_params& params)
      |   ^
```

2:
```
$ROOT/axom/quest/detail/PointFinder.hpp:281:14: warning: implicit capture of 'this' with a capture default of '=' is deprecated [-Wdeprecated-this-capture]
  281 |           if(m_meshWrapper->locatePointInCell(cellIdx, pt.data(), isopar.data()))
      |              ^
$ROOT/axom/quest/detail/PointFinder.hpp:273:7: note: add an explicit capture of 'this' to capture '*this' by reference
  273 |       AXOM_HOST_LAMBDA(IndexType i) {
      |       ^
$ROOT/include/axom/core/Macros.hpp:84:29: note: expanded from macro 'AXOM_HOST_LAMBDA'
   84 |   #define AXOM_HOST_LAMBDA [=] AXOM_HOST
      |
```

I built Axom with the following config and could reproduce warning 2, but not warning 1.

```
python3 ./config-build.py -hc ./host-configs/rzwhippet-toss_4_x86_64_ib-gcc@10.3.1.cmake -bt Release -DBLT_CXX_STD=c++20 -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Wshadow -Wpointer-arith -Wcast-qual -Wconversion -Wsign-conversion -Wformat=2 -Wnull-dereference -Woverloaded-virtual -Wnon-virtual-dtor -Wold-style-cast -Wunused -Wuninitialized -Wreorder -Wdeprecated-this-capture -Wundefined-inline"
```

### PR DESCRIPTION
**Pull request by BradWhitlock**
This PR resolves #1670, an issue about reported C++20 warnings with gcc. The PR also fixes some other warnings, including one in Equi-Z MIR where the fix should result in slightly less work.

### CODE REVIEW

File: src/axom/mint/tests/StructuredMesh_helpers.hpp [hunk 1]
```diff
@@ -31,6 +31,13 @@ namespace internal
 {
 constexpr double PI = 3.14;
 
+// Always define these sizes for 3D because some of the mesh methods in mint
+// meshes do not know their dimension until runtime and may contain 1D, 2D, 3D
+// implementations so the passed buffers better be large enough - and to silence
+// potential compiler warnings to that effect.
+constexpr int MAX_FACE_NODES = 6;
+constexpr int MAX_CELL_NODES = 8;
```
Comment (kennyweiss) [inline src/axom/mint/tests/StructuredMesh_helpers.hpp:39]: 👍

**Review by rhornung67 — APPROVED** [review]
Thank you @BradWhitlock
