### PR TITLE
Fixes some sidre memory leaks

### LINKED ISSUE #66: Memory leak in sidre::AttrValues
A user (@GamefanA) reported a memory leak in ``sidre::AttrValues``.

AttrValues has a member ``m_values``:
https://github.com/LLNL/axom/blob/339aa298e2ec20ea2147e894fd2f6da24c76961d/src/axom/sidre/core/AttrValues.hpp#L243-L247

That can be initialized here:
https://github.com/LLNL/axom/blob/339aa298e2ec20ea2147e894fd2f6da24c76961d/src/axom/sidre/core/AttrValues.cpp#L114-L119

But, it is not being deleted anywhere.

### PR DESCRIPTION
**Pull request by kennyweiss**
# Summary

This PR fixes some memory leaks and warnings in sidre
- It resolves #66 
- In solving that, I found another memory leak related to the ``DataStore``'s attributes
- I also fixed some memory leaks in the sidre tests using valgrind
- Finally, I updated some conduit headers that changed in conduit@0.4.0

### CODE REVIEW

File: src/axom/sidre/core/AttrValues.hpp [hunk 1]
```diff
@@ -240,7 +240,7 @@ class AttrValues
 
   ///////////////////////////////////////////////////////////////////
   //
-  typedef std::vector< Node > Values;
+  using Values = std::vector< Node >;
```
Comment (rhornung67) [inline src/axom/sidre/core/AttrValues.hpp]: 👍
