### PR TITLE
Initialize Array::m_executeOnGPU

### LINKED ISSUE #1432: axom::Array constructor crash on CUDA.
Code like the following resulted in Array::Array trying to initialize elements of a device-allocated array using placement new on the host. The code SEGV'd.

```
using ExecSpace = axom::CUDA_EXEC<256>;
const int allocatorID = axom::execution_space<ExecSpace>::allocatorID();
axom::Array<int> arr(n, n, allocatorID);

```
This method calls initialize() with 2 arguments, making the 3rd argument the detault of true, which is to default-construct.
https://github.com/LLNL/axom/blob/70b360815ebed6a25e6ae369bc5efeaa58cacdbc/src/axom/core/Array.hpp#L1084

https://github.com/LLNL/axom/blob/70b360815ebed6a25e6ae369bc5efeaa58cacdbc/src/axom/core/Array.hpp#L1591

I think the root of the problem could be that Array::m_executeOnGPU is not initialized anywhere. Valgrind was logging uninitialized memory in this area and m_executeOnGPU is probably the culprit.

Calling axom::Array<T>(n, n, allocatorID) where allocatorID is a CUDA allocator should not cause a SEGV and it should initialize the data as needed on device.

I was told that ATS might have some bearing here too.
```
zansel7{whitlocb}103: detect_ats
rzansel7     ATS detected
```

### PR DESCRIPTION
**Pull request by BradWhitlock**
# Summary
Lack of Array::m_executeOnGPU initialization played a role in causing host-initialization of device-allocated memory in certain situations. I was not able to create a reproducer on the develop branch but these changes eliminate warnings about uninitialized memory in axom::Array under Valgrind and fix the crashes on my MIR branch when using CUDA-allocated memory.

- This PR is a bugfix and closes #1432.
- It adds some initialization for Array::m_executeOnGPU, a bool that was causing warnings about uninitialized memory.

### CODE REVIEW

File: src/axom/core/Array.hpp [hunk 1]
```diff
@@ -966,8 +970,8 @@ class Array : public ArrayBase<T, DIM, Array<T, DIM, SPACE>>
   IndexType m_num_elements = 0;
   IndexType m_capacity = 0;
   double m_resize_ratio = DEFAULT_RESIZE_RATIO;
-  int m_allocator_id;
-  bool m_executeOnGPU;
+  int m_allocator_id = INVALID_ALLOCATOR_ID;
+  bool m_executeOnGPU {false};
```
Comment (rhornung67) [inline src/axom/core/Array.hpp:974]: Why do we use different variable initialization syntax? Do we have a convention that we follow?

Comment (BradWhitlock) [reply src/axom/core/Array.hpp:974]: I'm not aware of a convention. Point taken though. This file is using assignment-style initialization for the other members so I'll change to that for the bool.

File: src/axom/core/Array.hpp [hunk 2]
```diff
@@ -1164,6 +1170,8 @@ Array<T, DIM, SPACE>::Array(Array&& other) noexcept
   m_capacity = other.m_capacity;
   m_resize_ratio = other.m_resize_ratio;
   m_allocator_id = other.m_allocator_id;
+  m_executeOnGPU = axom::detail::getAllocatorSpace(m_allocator_id) ==
```
Comment (kennyweiss) [inline src/axom/core/Array.hpp:1173]: Suggestion: This is a one-liner, but might is somewhat tricky to get right, and perhaps subject to change, should it be a function here or in axom/core/memory_management?

File: src/axom/core/Array.hpp (hunk 1 above)
Comment (kennyweiss) [reply src/axom/core/Array.hpp]: @publixsubfan -- I think in the past, you had a reason to prefer the curly brace initialization syntax. Do you recall what it was? 

Once this is resolved, it might be good to update our coding conventions w/ a preference. At the very least, we should be consistent w/in a single file.

**Review by kennyweiss — APPROVED** [review]
Thanks @BradWhitlock  -- if possible, could you please add a regression test that triggers the behavior you observed?

File: src/axom/core/Array.hpp (hunk 2 above)
Comment (BradWhitlock) [reply src/axom/core/Array.hpp:1173]: Hi Kenny, good idea. I'm doing that now. I was running into trouble on CI anyway with MemorySpace::Device only existing when UMPIRE is enabled.

Comment (BradWhitlock) [reply src/axom/core/Array.hpp:1173]: As for a reproducer, I could not get it to happen with the test I wrote (so I junked it). The fixes do clear up my problems on CUDA though on my MIR branch.

Comment (kennyweiss) [reply src/axom/core/Array.hpp:1173]: From CI:
```
2024-10-01T19:41:44.0228174Z /home/axom/axom/src/axom/core/../../axom/core/Array.hpp:293:28: error: no member named 'Device' in 'axom::MemorySpace'
2024-10-01T19:41:44.0244447Z         axom::MemorySpace::Device;
2024-10-01T19:41:44.0245077Z         ~~~~~~~~~~~~~~~~~~~^
```
https://dev.azure.com/healy22/d4445b8f-6e95-49cd-9e5b-8c8ca1ccad31/_apis/build/builds/10807/logs/58

More reason to move this to a function. `Device` is only defined when Umpire is available.
See: https://github.com/LLNL/axom/blob/70b360815ebed6a25e6ae369bc5efeaa58cacdbc/src/axom/core/memory_management.hpp#L37-L47

+1 for the team for having CI configs w/o Umpire!

Comment (kennyweiss) [reply src/axom/core/Array.hpp:1173]: > As for a reproducer, I could not get it to happen with the test I wrote (so I junked it). The fixes do clear up my problems on CUDA though on my MIR branch.

Probably still good to have test cases that exercise the `true` and `false` branches

**Review by rhornung67 — APPROVED** [review]
@BradWhitlock looks reasonable. It would be good to think about adding tests to catch cases that may show breakages -- maybe make an issue that we can discuss?

**Comment by publixsubfan** [comment]
@rhornung67: I think we'd need to test with asan/ubsan enabled in order to reliably capture a problem like this. Alternatively, `-Weffc++` on Clang might be able to statically warn about uninitialized variables, but it might also spit out a bunch of other warnings that we'd have to work through.

**Comment by BradWhitlock** [comment]
I added a test that approximates what I was doing in my MIR branch. There was some weirdness with RelWithDebInfo but not a crash. The test calls a new function axom::isDeviceAllocator() to exercise it.
