### PR TITLE
Fix failing Mint test with intel18 release build

### LINKED ISSUE #90: Failing test in Intel@18 release build
One of the mint tests is failing in release builds on the ``intel@18`` compiler.

```
>./config-build.py -hc host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake -bt Release
...
>ctest -R mint_fem_single_fe -VV
...
117: [ RUN      ] mint_fem_single_fe.matrix_constructor_deepcopy
117: <axom>/src/axom/mint/tests/mint_fem_single_fe.cpp:874: Failure
117: Value of: utilities::isNearlyEqual( M.data()[i], physical_nodes[i] )
117:   Actual: true
117: Expected: false
117: <axom>/src/axom/mint/tests/mint_fem_single_fe.cpp:874: Failure
117: Value of: utilities::isNearlyEqual( M.data()[i], physical_nodes[i] )
117:   Actual: true
117: Expected: false
117: [  FAILED  ] mint_fem_single_fe.matrix_constructor_deepcopy (2 ms)
...
117:  1 FAILED TEST
1/1 Test #117: mint_fem_single_fe ...............***Failed    0.13 sec
```

Interestingly, it is passing in our ``intel@19`` host-config.

### PR DESCRIPTION
**Pull request by gzagaris**
# Summary

This PR fixes a failing Mint test, `mint_fem_single_fe`. The test was failing due to a compiler bug, which is circumvented by the changes introduced in this PR. In addition, this PR introduces some minor stylistic changes to modernize some of the code in `mint_fem_single_fe` test to C++11.

This PR resolves #90

### CODE REVIEW

File: src/axom/core/numerics/Matrix.hpp [hunk 1]
```diff
@@ -742,7 +742,9 @@ void Matrix< T >::swapColumns( IndexType icol, IndexType jcol )
   T* jcol_data = this->getColumn( jcol );
   for ( IndexType i=0 ; i < m_rows ; ++i )
   {
-    utilities::swap( icol_data[ i ], jcol_data[ i ] );
+    const T temp   = icol_data[ i ];
```
Comment (rhornung67) [inline src/axom/core/numerics/Matrix.hpp]: Any reason not to use std::swap here? Why do we have utilities::swap?

Comment (gzagaris) [reply src/axom/core/numerics/Matrix.hpp]: With intel@18 and optimizations turned on, this method was not working properly. 

We have `utilities::swap()` b/c we can host-device decorated, since, `std::swap` may not always work unless the compiler always inlines it.
