### PR TITLE
Fix Group::copyToConduitNode so that it handles lists correctly

### LINKED ISSUE #928: Group::copyToConduitNode doesn't work with lists
This line:

`      Node& g = n["groups"].fetch(group->getName());`

fails when `this` Group holds its item in the list format.  Here `group` is an unnamed child node and `getName` returns the empty string.  When using lists, we need to use `append` to create new unnamed child Nodes in a conduit list, rather than `fetch` which is used to created named child Nodes.

The same fix is needed when handling unnamed Views in a list.

### PR DESCRIPTION
**Pull request by nselliott**
# Summary

- This PR is a bug fix
- It does the following (modify list as needed):
  - Modifies `Group::copyToConduitNode` to handle Groups using the list format.j
  - Fixes #928 

This method had the assumption that all child items have a name.  This fix adds handling of unnamed items held in a list, and creates lists of unnamed child Nodes in the conduit output.

### CODE REVIEW

**Comment by nselliott** [comment]
I need to add a suitable test before merging.

**Review by gunney1 — APPROVED** [review]
Thanks @nselliott

**Review by rhornung67 — APPROVED** [review]
Thanks for the quick fix @nselliott

**Review by kennyweiss — APPROVED** [review]
Thanks @nselliott -- looks great!

Approved assuming there are sufficient tests (as you commented above)

File: src/axom/sidre/core/Group.cpp [hunk 1]
```diff
@@ -1340,19 +1340,33 @@ void Group::copyToConduitNode(Node& n) const
...
-
+    if(isUsingMap())
+    {
+      Node& v = n["views"].fetch(view->getName());
+      view->copyToConduitNode(v);
+    }
+    else
+    {
+      Node& v = n["views"].append();
+      view->copyToConduitNode(v);
```
Comment (kennyweiss) [inline src/axom/sidre/core/Group.cpp:1351]: Quick clarification -- how does this work?

My assumption is that it's appending an empty node `v` to `n["views"] and then `copyToConduitNode(v)` fills in `v`?
Is that right?

Comment (kennyweiss) [reply src/axom/sidre/core/Group.cpp:1351]: Looks like it:
https://github.com/LLNL/conduit/blob/de3a873068ba971405cfc003d3286673f2cedfcd/src/libs/conduit/conduit_node.hpp#L3971-L3975

Comment (nselliott) [reply src/axom/sidre/core/Group.cpp:1351]: Yes, your description is correct.

**Review by cyrush — APPROVED** [review]

**Review by agcapps — APPROVED** [review]
Thanks for the fix.
