### PR TITLE
Fixes from Alan Dayton (Many thanks!)

### LINKED ISSUE #1156: User code on BlueOS machine reports ptxas error when including IntersectionShaper.h
Error occurs when the source file ReadStl.cc has `#include "axom/quest.hpp"`:

```
ptxas ReadStl.ptx, line 5082; error   : Illegal operand type to instruction 'ld'
ptxas ReadStl.ptx, line 5082; error   : Unknown symbol '__unnamed_1_param_0'
ptxas ReadStl.ptx, line 5155; error   : Illegal operand type to instruction 'ld'
ptxas ReadStl.ptx, line 5155; error   : Unknown symbol '__unnamed_2_param_0'
ptxas ReadStl.ptx, line 5186; error   : Illegal operand type to instruction 'ld'
ptxas ReadStl.ptx, line 5186; error   : Unknown symbol '__unnamed_3_param_0'
ptxas fatal   : Ptx assembly aborted due to errors
```

If I comment out `#include "axom/quest/IntersectionShaper.hpp"` the errors do not occur.

### PR DESCRIPTION
**Pull request by agcapps**
# Summary

- This PR is a bugfix from @adayton1 
- It does the following:
  - Changes a loop in clip_impl.cpp to use a const ref to objects in a collection rather than make a copy each time through the loop
  - Fixes #1156 as suggested by @bmhan12 , by explicitly initializing Point values in object member arrays.

### CODE REVIEW

**Review by adayton1 — APPROVED** [review]
LGTM

**Review by rhornung67 — APPROVED** [review]
Thank you @adayton1 and @agcapps

**Comment by kennyweiss** [comment]
Looks like there were some failures w/ the cuda pro-e intersection tests w/ our `lassen-clang_10_0_1_cuda` and `lassen-xl_16_1_1_cuda` builds. E.g.:

```
314: [INFO] Load baseline .../axom/axom/data/quest/regression/quest_intersection_shaper/cuda/proeCase2.yaml 
314: [INFO] Load baseline .../axom/axom/data/quest/regression/quest_intersection_shaper/proeCase2.yaml 
314: [INFO] Comparing to baseline  
314: 
314: maxdiff: 
314:   shape_vol_frac_shape0: 0.142101284958428
314: 
314: .../axom/axom/src/axom/quest/tests/quest_intersection_shaper.cpp:399: Failure
314: Expected equality of these values:
314:   success
314:     Which is: false
314:   true
314: 
314: [  FAILED  ] IntersectionShaperTest.proeCase_cuda (476 ms)

```

File: src/axom/primal/geometry/Polyhedron.hpp [hunk 1]
```diff
@@ -205,8 +205,8 @@ class NeighborCollection
   }
 
 private:
-  std::int8_t num_nbrs[MAX_VERTS];
-  VertexNbrs nbrs[MAX_VERTS];
+  std::int8_t num_nbrs[MAX_VERTS] {};
+  VertexNbrs nbrs[MAX_VERTS] {};
```
Comment (bmhan12) [inline src/axom/primal/geometry/Polyhedron.hpp:209]: The cuda test case passes when I revert this default member initalizer change. I am not sure why this causes problem on device...

Comment (agcapps) [reply src/axom/primal/geometry/Polyhedron.hpp:209]: !!!  Well, thank you for checking on that, Brian.  That's very odd.

Comment (kennyweiss) [reply src/axom/primal/geometry/Polyhedron.hpp:209]: Great catch @bmhan12 -- looks like uninitialized memory

**Comment by kennyweiss** [comment]
Thanks @adayton1 and @agcapps !

**Comment by white238** [comment]
@agcapps  is this ready to be merged after pipelines pass?

**Comment by agcapps** [comment]
> @agcapps is this ready to be merged after pipelines pass?

Yes, it is.

**Comment by agcapps** [comment]
@bmhan12 , any further comment on this MR?

**Review by bmhan12 — APPROVED** [review]
> @bmhan12 , any further comment on this MR?

Looks good to me!
