### PR TITLE
Fixes a host function called from host device function.

### LINKED ISSUE #1337: Calling host function in host device function.
The following was reported on Teams. A host function is being called from a host_device function. In this case, the std::numeric_limits<>::max() function is being called and it is host-only. Calls like this could affect Axom on CUDA or HIP.

```
/usr/gapps/bdiv/blueos_3_ppc64le_ib_p9/clang-14-cuda-11.8-gcc831/axom/0.9.1a-cuda/include/axom/spin/policy/LinearBVH.hpp(82): warning #20013-D: calling a constexpr __host__ function("max") from a __host__ __device__ function("operator()") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
 
Line looks to be
      double sqDistR = r.isValid() ? primal::squared_distance(p, r.getCentroid())
                                   : std::numeric_limits<double>::max();
```

* Fix the reported call and others like it

### PR DESCRIPTION
**Pull request by BradWhitlock**
# Minor compilation warning removal

- This PR resolves #1337.
- It changes some files to reduce/eliminate compiler warnings about host-only functions being called from host_device functions.
  - Changes numeric_limits<>::max() to floating_point_limits<>::max()
  - Added AXOM_HOST_DEVICE to Sphere to remove some warnings
  - Change IndirectionPolicy so for GPU cases it does not try to reference std::vector::operator[]
  - Fix some sign change warnings

Note - there are still many more warnings where host code is called from host-device functions. This matters for CUDA/HIP systems where functions need to be available on the GPU, though not all Axom functionality needs to probably be on the GPU.  It seems like AXOM_HOST_DEVICE support is being added gradually to Axom so we have a mix of these warnings. The worst offenders are slam (various Maps) and spin. 

I looked at some of the slam issues that caused the host from host_device warning to appear. Many come from constructors/destructors and other methods for maps and iterators not yet having AXOM_HOST_DEVICE. Should they even? I did not include those changes because the changes started to feel like a slippery slope.

### CODE REVIEW

File: src/axom/slam/policies/IndirectionPolicies.hpp [hunk 1]
```diff
@@ -105,10 +105,14 @@ struct IndexedIndirection : public BasePolicy
...
     abort();
+  #else
+    // Always return a value.
+    return buf[pos];
   #endif
-#endif
+#else
     // Always return a value.
     return buf[pos];
+#endif
```
Comment (kennyweiss) [inline src/axom/slam/policies/IndirectionPolicies.hpp:115]: Is this change meant to be more explicit? 

My read is that the previous behavior always called `return buf[pos]` (regardless of whether `AXOM_DEVICE_CODE` is defined) and the updated behavior does the same.

File: src/axom/slam/policies/IndirectionPolicies.hpp [hunk 2]
```diff
@@ -126,10 +130,14 @@ struct IndexedIndirection : public BasePolicy
...
```
Comment (kennyweiss) [inline src/axom/slam/policies/IndirectionPolicies.hpp:140]: Same question as for `getIndirection()` a few lines up

**Review by kennyweiss — APPROVED** [review]
Thanks @BradWhitlock!

Note: I think this PR is related to https://github.com/LLNL/axom/pull/1196
Tag: @rhornung67

File: src/axom/slam/policies/IndirectionPolicies.hpp (hunk 1 above)
Comment (BradWhitlock) [reply src/axom/slam/policies/IndirectionPolicies.hpp:115]: I suppose I could have removed the comment " Always return a value". The problem for the CUDA/HIP branches of these functions was that an STLVectorIndirection was passed into the IndexedIndirection and the operator[] it ends up using is not a host-device function and never could be, resulting in a lot of compilation warnings on rzansel.

**Comment by kennyweiss** [comment]
@rhornung67 -- would you be ok w/ merging this PR and then renaming it/incorporating it into the work you've done in #1196?

**Review by bmhan12 — APPROVED** [review]

**Comment by rhornung67** [comment]
@BradWhitlock a while back, I was toying around with a related issue (see https://github.com/LLNL/axom/pull/1196). Would that be an easier way to fix this type of issue?

**Comment by rhornung67** [comment]
> @rhornung67 -- would you be ok w/ merging this PR and then renaming it/incorporating it into the work you've done in #1196?

Sure. I need to get back to that, but I keep getting distracted to other things.

**Comment by BradWhitlock** [comment]
@rhornung67  - Adding a full-blown axom::numeric_limits<> sounds useful to me. I wasn't really aware of that work in #1196 so I used a related axom::numerics::floating_point_limits<>::max() function that was in the code today. I changed the numeric_limits in 2 places that were marked AXOM_HOST_DEVICE.
