### PR TITLE
Bugfix point in cell query

### LINKED ISSUE #755: Fix `point_in_cell` tests
The `point_in_cell_mfem` test in `quest` has been sporadically failing our CI tests lately.
* It has been taking a long time and occasionally timing out on our LC / docker tests
* It has been failing on Windows builds that have TPL builds enabled. 

(Note: our Windows CI does not build against TPLs, but our manual builds do, 
 e.g. https://github.com/LLNL/axom/actions/runs/1604425099 )

### PR DESCRIPTION
**Pull request by kennyweiss**
# Summary

- This PR is a bugfix
- It resolves #755 
- It adds a missing 3rd parameter to the `PointInCell` class. The 3rd and 4th parameters have default values, and the code was supplying the 1st, 2nd and 4th parameters.
  - **Update:** I had to remove the fourth parameter from `PointInCell` invocation in the `point_in_cell_mfem` unit tests. This will be resolved in #757 
- It also initializes a variable that was not being initialized in non-RAJA runs (like our manual Windows CI, which have `mfem` and `conduit`, but do not yet have `raja` or `umpire`)

### CODE REVIEW

File: src/axom/quest/tests/quest_point_in_cell_mfem.cpp [hunk 1]
```diff
@@ -107,16 +105,17 @@ template <int DIM, typename ExecSpace>
 class PointInCellTest : public ::testing::Test
 {
 public:
-  typedef axom::primal::BoundingBox<double, DIM> BBox;
-  typedef axom::primal::Point<double, DIM> SpacePt;
-  typedef axom::primal::Vector<double, DIM> SpaceVec;
+  using BBox = axom::primal::BoundingBox<double, DIM>;
```
Comment (rhornung67) [inline src/axom/quest/tests/quest_point_in_cell_mfem.cpp:108]: 👍

File: src/axom/quest/tests/quest_point_in_cell_mfem.cpp [hunk 2]
```diff
@@ -107,16 +105,17 @@ template <int DIM, typename ExecSpace>
...
+  using SpacePt = axom::primal::Point<double, DIM>;
+  using SpaceVec = axom::primal::Vector<double, DIM>;
   // _quest_pic_typedef_start
-  typedef axom::primal::Point<int, DIM> GridCell;
+  using GridCell = axom::primal::Point<int, DIM>;
```
Comment (rhornung67) [inline src/axom/quest/tests/quest_point_in_cell_mfem.cpp:112]: Should the int type here be the IndexType below?

**Review by rhornung67 — APPROVED** [review]
Only one minor question to possibly address.

**Review by agcapps — APPROVED** [review]
Thank you, @kennyweiss , for finding and fixing that bug.

File: src/axom/quest/tests/quest_point_in_cell_mfem.cpp [hunk 3]
```diff
@@ -297,7 +291,7 @@ class PointInCellTest : public ::testing::Test
     // Generate a PointInCell structure over the mesh
     axom::utilities::Timer constructTimer(true);
     // _quest_pic_init_start
-    PointInCellType spatialIndex(m_mesh, GridCell(25).data(), m_allocatorID);
+    PointInCellType spatialIndex(m_mesh, GridCell(25).data(), m_EPS);
```
Comment (kennyweiss) [inline src/axom/quest/tests/quest_point_in_cell_mfem.cpp:294]: @kanye-quest -- I had to remove the fourth parameter `m_allocatorID` from the `PointInCell` constructor invocations. 
It was running into segfaults on blueos in the `BitSet` constructor (specifically when calling `Array::fill`) since `BitSet` does not (yet?) support modification operations on the device.

Is this something you were planning to continue working on?

**Review by white238 — APPROVED** [review]
Thanks for tracking this down @kennyweiss

File: src/axom/quest/tests/quest_point_in_cell_mfem.cpp (hunk 2 above)
Comment (kennyweiss) [reply src/axom/quest/tests/quest_point_in_cell_mfem.cpp]: Thanks -- I made the change.
I also improved the consistency of the types for the `PointInCell` classes and worked through a few other issues.

File: src/axom/quest/tests/quest_point_in_cell_mfem.cpp (hunk 3 above)
Comment (kennyweiss) [reply src/axom/quest/tests/quest_point_in_cell_mfem.cpp:294]: @kanye-quest and I discussed this offline. I created #757 to track this.

**Comment by kennyweiss** [comment]
Manual Windows TPL build is clean: https://github.com/LLNL/axom/actions/runs/1660006057

File: src/axom/quest/tests/quest_point_in_cell_mfem.cpp [hunk 4]
```diff
@@ -390,29 +387,47 @@ class PointInCellTest : public ::testing::Test
...
+      // Reconstruct points in space from isoparametric coords on an element
+      for(int idx = 0; idx < SZ; ++idx)
+      {
+        spatialIndex.reconstructPoint(eltId,
+                                      isoPts[idx].data(),
+                                      spacePts[idx].data());
+      }
+
+      // locate the reconstructed points (using EXEC space)
+      spatialIndex.locatePoints(spacePts.view(), foundIDs.data(), foundIso.data());
```
Comment (kennyweiss) [inline src/axom/quest/tests/quest_point_in_cell_mfem.cpp:410]: Investigating why our CI tests have been really slow for this test...

This call to `locatePoints()` was being called once for each integration point of each element, and has several kernels.
Since `reconstructPoint` is using serial mfem functionality, I converted it to one `locatePoints` per element.

Comment (kennyweiss) [reply src/axom/quest/tests/quest_point_in_cell_mfem.cpp:410]: By really slow, I mean that the test can take >10 minutes in the CI (sometimes considerably more). 
The test only takes a few seconds when run locally.

**Review by kanye-quest — APPROVED** [review]

File: src/axom/quest/tests/quest_point_in_cell_mfem.cpp (hunk 4 above)
Comment (kennyweiss) [reply src/axom/quest/tests/quest_point_in_cell_mfem.cpp:410]: Seems to have done the trick.
The test is down to a few minutes compared to 10-20 minutes.

E.g. for the clang@10 build:

#### Before
> 273/273 Test #253: quest_point_in_cell_mfem .................   Passed  899.56 sec
https://lc.llnl.gov/gitlab/axom/axom/-/jobs/514998#L6314

#### After
> 259/259 Test #253: quest_point_in_cell_mfem ................   Passed   74.22 sec
https://lc.llnl.gov/gitlab/axom/axom/-/jobs/515255#L7445


As a future optimization, we should consider performing all the point locations in a single call to `locatePoints()`, which would likely bring the results back down to a few seconds.

Comment (white238) [reply src/axom/quest/tests/quest_point_in_cell_mfem.cpp:410]: you are so picky @kennyweiss ... 10 minutes is not good enough for you!?
