### PR TITLE
Fixes build in configurations without MPI

### LINKED ISSUE #849: IOBaton included in non-mpi configs
@jcs15c was running on Windows in a configuration without MPI and encountered an error in `IOBaton.hpp` about including mpi.

Specifically, `IOBaton` should not be included from anything in a non-mpi configuration.

### PR DESCRIPTION
**Pull request by kennyweiss**
# Summary

- This PR is a bugfix
- It fixes the build for configurations without MPI. 
- There were two issues 
    - one had an unguarded inclusion of spio (which is only available when MPI is available. See: #849.
       Looks like I introduced this problem in #837 when I got rid of `sidre/core/sidre.hpp`
    - the other was for configs with C2C but not MPI.
- Resolves #849

### CODE REVIEW

File: src/axom/quest/interface/internal/QuestHelpers.cpp [hunk 1]
```diff
@@ -13,8 +13,12 @@
   #include "axom/quest/readers/PSTLReader.hpp"
 #endif
 
-#if defined(AXOM_USE_MPI) && defined(AXOM_USE_C2C)
-  #include "axom/quest/readers/PC2CReader.hpp"
+#if defined(AXOM_USE_C2C)
+  #if defined(AXOM_USE_MPI)
+    #include "axom/quest/readers/PC2CReader.hpp"
```
Comment (rhornung67) [inline src/axom/quest/interface/internal/QuestHelpers.cpp:18]:
```suggestion
    #include "axom/quest/readers/C2CReader_MPI.hpp"
```
Would changing the file name make it clearer? 'PC2C..." seems too terse to me.

Comment (kennyweiss) [reply src/axom/quest/interface/internal/QuestHelpers.cpp:18]: Note: We also have an `STLReader` and a corresponding `PSTLReader`.

I think renaming the class with the `_MPI` suffix might obscure the intent. 
i.e. the "parallel" part is the important part, rather than "MPI"

Would you prefer something like `Parallel{C2C,STL}Reader`, or perhaps `Par{C2C,STL}Reader` ?

Comment (kennyweiss) [reply src/axom/quest/interface/internal/QuestHelpers.cpp:18]: Thoughts from others about (re)-naming these files and classes? 

I'd be ok with any of the following:
1. PSTLReader / PC2CReader (current, keep as is)
2. ParSTLReader / ParC2CReader
3. ParallelSTLReader / ParallelC2CReader
4. STLReader_MPI / C2CReader_MPI

Additional notes/factors to consider: 
* At least some users are using `PSTLReader` and would need to make changes
* The way the class works is that it reads the file on rank 0 and sends the data to the other ranks.

Comment (kennyweiss) [reply src/axom/quest/interface/internal/QuestHelpers.cpp:18]: If we don't have immediate consensus, perhaps it would be best to move this to a separate issue so we can have a more focused discussion (?)

**Review by agcapps — APPROVED** [review]
Thanks for the build fixes, Kenny.

Yes, PC2CReader / C2CReader is terse.  As is PSTLReader / STLReader.  I like this terseness, but if others would like a larger difference between names, I'll be willing to discuss.

**Comment by rhornung67** [comment]
> Thanks for the build fixes, Kenny.
> 
> Yes, PC2CReader / C2CReader is terse. As is PSTLReader / STLReader. I like this terseness, but if others would like a larger difference between names, I'll be willing to discuss.

brevity is the spice of life, i guess.

File: src/axom/quest/interface/internal/QuestHelpers.cpp (hunk 1 above)
Comment (kennyweiss) [reply src/axom/quest/interface/internal/QuestHelpers.cpp:18]: Thanks @agcapps -- I also vote for leaving it as is for now. 

I'll create an issue to continue the conversation.

**Review by gunney1 — APPROVED** [review]
Seems pretty straight forward to me.  Thanks.

**Review by jcs15c — APPROVED** [review]
This fixed the issue I was having, thank you!
