### PR TITLE
fix #1747

### LINKED ISSUE #1747: Guard HDF5 usage in Sina
Using #1740, I built a library set for a minimal Sina build without HDF5 using:
> ./scripts/uberenv/uberenv.py --spec "+adiak+conduit~hdf5~umpire~raja components=sina %clang_19"

This revealed some compiler errors related to unguarded HDF5 usage in `sina:::Document`

```
<axom>/src/axom/sina/core/Document.cpp:544:23: 
error: no member named 'hdf5_read_info' in namespace 'conduit::relay::io'
  544 |   conduit::relay::io::hdf5_read_info(original_file_path, endpoint, metadata_only);
      |   ~~~~~~~~~~~~~~~~~~~~^
<axom>/src/axom/sina/core/Document.cpp:1102:18: error: too many arguments to function call, expected 0, have 1
 1102 |   msgNode.append("Failed to append Sina HDF5: Axom wasn't build with HDF5");
      |   ~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<axom>/uberenv_libs/llvm-19.1.3/conduit-0.9.5-o34xnkmn2nrno7ngmunowu5kcp2jzxn2/include/conduit/conduit_node.hpp:3995:13: note: 'append' declared here
 3995 |     Node   &append();
      |             ^


<axom>/src/axom/sina/core/Document.cpp:1086:55: warning: unused parameter 'hdf5FilePath' [-Wunused-parameter]
 1086 | conduit::Node appendDocumentToHDF5(const std::string &hdf5FilePath,
      |                                                       ^
<axom>/src/axom/sina/core/Document.cpp:1087:52: warning: unused parameter 'newData' [-Wunused-parameter]
 1087 |                                    const Document &newData,
      |                                                    ^
<axom>/src/axom/sina/core/Document.cpp:1088:46: warning: unused parameter 'mergeProtocol' [-Wunused-parameter]
 1088 |                                    const int mergeProtocol,
      |                                              ^
<axom>/src/axom/sina/core/Document.cpp:1089:47: warning: unused parameter 'skipValidation' [-Wunused-parameter]
 1089 |                                    const bool skipValidation)
      |                                               ^
4 warnings and 2 errors generated.
```

Related issue: #1745

### PR DESCRIPTION
**Pull request by doutriaux1**
# Summary

- This PR is a bugfix
- It does the following (modify list as needed):
  - compiles and passes test if sina is built and axom is w/o hdf5

### CODE REVIEW

File: src/axom/sina/core/Document.cpp [hunk 1]
```diff
@@ -1098,9 +1102,7 @@ conduit::Node appendDocumentToHDF5(const std::string &hdf5FilePath,
   appendTo.close();
   return msgNode;
 #else
-  conduit::Node msgNode = conduit::Node(conduit::DataType::list());
-  msgNode.append("Failed to append Sina HDF5: Axom wasn't build with HDF5");
-  return msgNode;
+  throw std::runtime_error("Failed to append Sina HDF5: Axom wasn't build with HDF5");
```
Comment (adayton1) [inline src/axom/sina/core/Document.cpp]: build -> built

**Comment by doutriaux1** [comment]
@kennyweiss @rhornung67 @white238 I don't have enough privileges to merge this, could one of you press the merge button please? Thanks!
